### Add products
POST http://localhost:3000/api/v1/add-product/
Content-Type: application/json

{
    "name": "Arthur Morgan Action Figure",
    "description": "Arthur Morgan from Red Redemption 2",
    "price": 49,
    "discount_price": null,
    "stock_quantity": 105,
    "category_id": 252,
    "brand": "GMS",
    "sku": null,
    "weight": "0.2",
    "dimensions": null,
    "color": ["Golden", "Black", "Normal"],
    "size": ["Small", "Medium", "Large"],
    "material": "Metal",
    "condition": "New",
    "status": "ACTIVE",
    "image_urls": [{
        "main": "main.png",
        "views": [
            "view1.png",
            "view2.png",
            "view3.png"
        ]
    }], 
    "rating": 4.3,
    "total_reviews": 20,
    "sold_count": 43
}

### Get my products
GET http://localhost:3000/api/v1/get-my-products